version: '3.8'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_DATABASE: news_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db